### ISSUE TITLE
Bot not started

### ISSUE THREAD

**Issue by Salyaris1488** [Tkd-Alex/Telegram-InstaPy-Scheduling#11]
After starting - console just freeze, and nothing hapend.
Bot not responding
Token and id correct, python-telegram-bot installed
Logs are empty

![qfe3xrie](https://user-images.githubusercontent.com/42358714/44063753-9a65bb5a-9f6a-11e8-885e-14b487e548bf.jpg)

**Comment by Tkd-Alex** [comment]
uhmm i think is all ok, have you tried to send a command to your bot? `\/help`

**Comment by Salyaris1488** [comment]
Yep, but bot not responding for any commands

**Comment by Tkd-Alex** [comment]
Try if the echobot example work on your enviroment

https://github.com/python-telegram-bot/python-telegram-bot/blob/master/examples/echobot.py

**Comment by Salyaris1488** [comment]
I've got error
`C:\Users\Администратор.WIN-10SCQ\AppData\Local\Programs\Python\Python37>python echobot.py
Traceback (most recent call last):
  File "C:\Users\Администратор.WIN-10J2Q\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Администратор.WIN-10SUJ2Q\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 360, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Администратор.WIN-10J2Q\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 857, in _validate_conn
    super(HTTPSConnectionPool, self)._validate_conn(conn)
  File "C:\Users\Администратор.WIN-10SC9Q\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 289, in _validate_conn
    conn.connect()
  File "C:\Users\Администратор.WIN-1FUJ2Q\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connection.py", line 326, in connect
    ssl_context=context)
  File "C:\Users\Администратор.WIN-10SCJ2Q\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\ssl_.py", line 324, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "C:\Users\Администратор.WIN-10Q\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 412, in wrap_socket
    session=session
  File "C:\Users\Администратор.WIN-10SQ\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 850, in _create
    self.do_handshake()
  File "C:\Users\Администратор.WIN-10SC9\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1108, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Администратор.WIN-10S2Q\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 195, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Users\Администратор.WIN-10SC9PQ\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 70, in request
    **urlopen_kw)
  File "C:\Users\Администратор.WIN-10SC9P\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Администратор.WIN-10SC9Q\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Администратор.WIN-10SC\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 647, in urlopen
    raise SSLError(e)
telegram.vendor.ptb_urllib3.urllib3.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "echobot.py", line 56, in <module>
    main()
  File "echobot.py", line 27, in main
    update_id = bot.get_updates()[0].update_id
  File "C:\Users\Администратор.WIN-10SC9\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 60, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Users\Администратор.WIN-10SC9P\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 1768, in get_updates
    result = self._request.post(url, data, timeout=float(read_latency) + float(timeout))
  File "C:\Users\Администратор.WIN-10SC9PF\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 278, in post
    **urlopen_kwargs)
  File "C:\Users\Администратор.WIN-10SC9PJ\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 201, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:1045)`

**Comment by Tkd-Alex** [comment]
uhmm i think you have a problem with your enviroment
try to setup a virtualenv

**Comment by Salyaris1488** [comment]
virtualenv too hard for me)
I tried to run bot at another PC and received same error

**Comment by Salyaris1488** [comment]
![7jq0cpp](https://user-images.githubusercontent.com/42358714/44092989-bb208d32-9fda-11e8-96c2-1555199e3197.png)

**Comment by Tkd-Alex** [comment]
maybe your telegram token is wrong or you have a problem with config parser.
follow issue #4

if not help, try to download the new version of Telegram-InstaPy-Scheduling

**Comment by Salyaris1488** [comment]
Thanks, I found the problem
In my country telegram blocked, and I need proxy for bot
