### ISSUE TITLE
set a scheduled job

### ISSUE THREAD

**Issue by HCWcoder** [Tkd-Alex/Telegram-InstaPy-Scheduling#19]
```
C:\Users\JayPixx\Documents\GitHub\InstaPy>python main.py
An uncaught error was raised while executing job test
Traceback (most recent call last):
  File "C:\Users\JayPixx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\jobqueue.py", line 245, in tick
    job.run(self.bot)
  File "C:\Users\JayPixx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\jobqueue.py", line 372, in run
    self.callback(bot, self)
  File "main.py", line 74, in exec_process
    if process_array[job.name].isAlive():
AttributeError: 'Process' object has no attribute 'isAlive'
```

/set username test(job name) biglikers date

**Comment by xmacedo** [comment]
This issue resolved, after commit in 12/13/2018. #[https://github.com/Tkd-Alex/Telegram-InstaPy-Scheduling/commit/8c2075c7e18b0a861d55a12a52a0017a15c35814](url)

**Comment by Tkd-Alex** [comment]
Yes, check the last commit :)
Thank you for reporting!
