### ISSUE TITLE
Message: 'chromedriver' executable needs to be in PATH.

### ISSUE THREAD

**Issue by astounded83** [Tkd-Alex/Telegram-InstaPy-Scheduling#21]
Where do I define "**headless_browser=True**" in scripts.py in order to run the script in the background?

`ERROR [2018-12-15 13:29:39] [randomuser]  Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/assets/chromedriver'
`

**Comment by Tkd-Alex** [comment]
Check this issue on InstaPy repository.
I think you haven't copy the chromedriver in assets folder inside your InstaPy path

**Comment by astounded83** [comment]
That can't be the problem, the script runs in the InstaPy folder.  The question is where to define headless_browser=True.

**Comment by Tkd-Alex** [comment]
I did not understand your problem.
If you don't know how to define __headless_browser=True__ , why you have report a __chromedriver__ error? 

The following code is an example for you:
```python
def like_by_feed(InstaPy, username, password, proxy=None):
    try:
        session = InstaPy(
            username=username, 
            password=password, 
            proxy_chrome_extension=proxy_chrome, 
            nogui=True, 
            show_logs=True, 
            headless_browser=True,
            disable_image_load=True
        )
        session.login()
```

**Comment by astounded83** [comment]
That's how I defined it, of course. But this leads to the following error:

`Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 76, in start
    stdin=PIPE)
  File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.5/dist-packages/assets/chromedriver'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 381, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    self.service.start()
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/common/service.py", line 83, in start
    os.path.basename(self.path), self.start_error_message)
selenium.common.exceptions.WebDriverException: Message: 'chromedriver' executable needs to be in PATH. Please see https://sites.google.com/a/chromium.org/chromedriver/home


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/astounded83/InstaPy/extensions/Telegram/scripts.py", line 15, in awesome
    disable_image_load=True)
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 256, in __init__
    self.set_selenium_local_session()
  File "/usr/local/lib/python3.5/dist-packages/instapy/instapy.py", line 385, in set_selenium_local_session
    Settings.chromedriver_location))
instapy.instapy.InstaPyError: ensure chromedriver is installed at /usr/local/lib/python3.5/dist-packages/assets/chromedriver

Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/home/astounded83/InstaPy/extensions/Telegram/process.py", line 73, in run
    self.bot.send_message(self.chat_id, text=parse_loglines( lines[-20:] ), parse_mode='HTML')
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/usr/local/lib/python3.5/dist-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
`

**Comment by astounded83** [comment]
Maybe. Anyway, he's calling the wrong path.

**Comment by astounded83** [comment]
I moved the files to the base directory of InstaPy, now it works.
