### ISSUE TITLE
module not found error

### ISSUE THREAD

**Issue by Jenuan** [Tkd-Alex/Telegram-InstaPy-Scheduling#3]
i keep getting this error

Traceback (most recent call last):
  File "C:\Users\jenua\OneDrive\Documents\InstaPy\Telegram-InstaPy-Scheduling\telegram-instapy.py", line 7, in <module>
    from telegram.ext import Updater, CommandHandler, Job, CallbackQueryHandler
ModuleNotFoundError: No module named 'telegram'

**Comment by Tkd-Alex** [comment]
` pip install python-telegram-bot --upgrade `

**Comment by lee-android** [comment]
Thank you, that seems to have done it. However, now I'm getting this error:

python3 telegram-instapy.py
Traceback (most recent call last):
  File "telegram-instapy.py", line 244, in <module>
    main()
  File "telegram-instapy.py", line 217, in main
    updater = Updater(telegram_token)
  File "/usr/local/lib/python3.6/site-packages/telegram/ext/updater.py", line 122, in __init__
    self.bot = Bot(token, base_url, request=self._request)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 108, in __init__
    self.token = self._validate_token(token)
  File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 134, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token

I have already followed the provided steps to create a bot, and I also copied the necessary information in the config.ini file as well.
