### ISSUE TITLE
"Chrome failed to start: exited abnormally"

### ISSUE THREAD

**Issue by lw507632** [Tkd-Alex/Telegram-InstaPy-Scheduling#36]
Hello everyone!

I'm new to this tool, i try to run it on a raspberry, everything is ok, the main run as expected

But when i try to start a job via Telegram, i have this error

```
ERROR [2019-02-16 19:46:05] [dzdiscov**]  Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)
Traceback (most recent call last):
  File "/home/pi/Projects/InstaPy/instapy/browser.py", line 122, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/chrome/webdriver.py", line 81, in _init_
    desired_capabilities=desired_capabilities)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 157, in _init_
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.5/dist-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.79-v7+ armv7l)

Traceback (most recent call last):
  File "/home/pi/Projects/Telegram-InstaPy-Scheduling/scripts.py", line 46, in followoran
    session = InstaPy(username=username, password=password, headless_browser=False)
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 263, in _init_
    self.set_selenium_local_session()
  File "/home/pi/Projects/InstaPy/instapy/instapy.py", line 315, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.instapy.InstaPyError: ensure chromedriver is installed at `/home/pi/Projects/InstaPy/assets/chromedriver
```

My settings.json file is well setted (with the instapy folder path inside) and my scripts runs perfectly without this tool. Maybe someone had the same problem before? 

Thank you :)

**Comment by lw507632** [comment]
Fixed simply by turning ` headless=True` in the InstaPy constructor

link to the issue : [Instapy related issue](https://github.com/timgrossmann/InstaPy/issues/2386)
