### ISSUE TITLE
cannot import name 'instapy'

### ISSUE THREAD

**Issue by lee-android** [Tkd-Alex/Telegram-InstaPy-Scheduling#4]
error: 

Traceback (most recent call last):
  File "telegram-instapy.py", line 9, in <module>
    from instapy import instapy
ImportError: cannot import name 'instapy'

if you could help me with this, I'd appreciate it greatly.

**Comment by Tkd-Alex** [comment]
Clone the repo [https://github.com/timgrossmann/InstaPy](https://github.com/timgrossmann/InstaPy) and copy the _instapy_ folder inside this repo.

[https://github.com/timgrossmann/InstaPy/tree/master/instapy](https://github.com/timgrossmann/InstaPy/tree/master/instapy) 

![image](https://user-images.githubusercontent.com/14061593/34948735-4c66b474-fa0e-11e7-8f32-08209e5e6f28.png)

**Comment by lee-android** [comment]
Thank you, that seems to have done it. However, now I'm getting this error:

python3 telegram-instapy.py
Traceback (most recent call last):
File "telegram-instapy.py", line 244, in 
main()
File "telegram-instapy.py", line 217, in main
updater = Updater(telegram_token)
File "/usr/local/lib/python3.6/site-packages/telegram/ext/updater.py", line 122, in init
self.bot = Bot(token, base_url, request=self._request)
File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 108, in init
self.token = self._validate_token(token)
File "/usr/local/lib/python3.6/site-packages/telegram/bot.py", line 134, in _validate_token
raise InvalidToken()
telegram.error.InvalidToken: Invalid token

I have already followed the provided steps to create a bot, and I also copied the necessary information in the config.ini file as well.

**Comment by Tkd-Alex** [comment]
This error is reported by telegram-api when the token still not valid. Try to print the readed token from config.ini at first line of main() method.
`
def main():
print (telegram_token)
updater = Updater(telegram_token)
`
Compare printing with your token get from BotFather.

**Comment by Tkd-Alex** [comment]
This error is reported by telegram-api when the token still not valid. Try to print the readed token from config.ini at first line of main() method.
`
def main():
print (telegram_token)
updater = Updater(telegram_token)
`
Compare printing with your token get from BotFather.

**Comment by luigifaticoso** [comment]
```
Traceback (most recent call last):
  File "telegram-instapy.py", line 292, in <module>
    main()
  File "telegram-instapy.py", line 265, in main
    updater = Updater(telegram_token)
  File "/Library/Python/2.7/site-packages/telegram/ext/updater.py", line 122, in __init__
    self.bot = Bot(token, base_url, request=self._request)
  File "/Library/Python/2.7/site-packages/telegram/bot.py", line 108, in __init__
    self.token = self._validate_token(token)
  File "/Library/Python/2.7/site-packages/telegram/bot.py", line 134, in _validate_token
    raise InvalidToken()
```
I'm getting the same error using the right token printed in the **main** and in the 
`/Library/Python/2.7/site-packages/telegram/bot.py`

**Comment by Tkd-Alex** [comment]
![image](https://user-images.githubusercontent.com/14061593/35116192-d3f791d2-fc8a-11e7-8759-4a8d6967c24f.png)
This is an example. This working.
Try to set manually token in variable without using ConfigParser.

**Comment by luigifaticoso** [comment]
This works! Nice

**Comment by ArielEcker** [comment]
I have an similar error... can you help me?

Traceback (most recent call last):
  File "C:\Ariel\2018\InstaPy-master\telegram-instapy.py", line 232, in <module>
    main()
  File "C:\Ariel\2018\InstaPy-master\telegram-instapy.py", line 205, in main
    updater = Updater(telegram_token)
  File "C:\Python 3.6.4\lib\site-packages\telegram\ext\updater.py", line 122, in __init__
    self.bot = Bot(token, base_url, request=self._request)
  File "C:\Python 3.6.4\lib\site-packages\telegram\bot.py", line 108, in __init__
    self.token = self._validate_token(token)
  File "C:\Python 3.6.4\lib\site-packages\telegram\bot.py", line 134, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
>>>
