### ISSUE TITLE
Exception in thread updater

### ISSUE THREAD

**Issue by Belsea** [Tkd-Alex/Telegram-InstaPy-Scheduling#44]
Hi, 
I've encountered this issue and I can't find a solution in whichever older issue here and related.
This is my third setup on a pc with freshly installed python and instapy, so everything is up to date; the other two went smooth. Is someone able to pull a solution out of the hat?

```
Exception in thread updater:
Traceback (most recent call last):
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\updater.py", line 156, in _thread_wrapper
    target(*args, **kwargs)
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\updater.py", line 273, in _start_polling
    self._bootstrap(bootstrap_retries, clean=clean, webhook_url='', allowed_updates=None)
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\updater.py", line 440, in _bootstrap
    'bootstrap del webhook', bootstrap_interval)
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\updater.py", line 333, in _network_loop_retry
    onerr_cb(te)
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\updater.py", line 432, in bootstrap_onerr_cb
    raise exc
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\updater.py", line 319, in _network_loop_retry
    if not action_cb():
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\ext\updater.py", line 410, in bootstrap_del_webhook
    self.bot.delete_webhook()
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\bot.py", line 2097, in delete_webhook
    result = self._request.post(url, data, timeout=timeout)
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\utils\request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "C:\Users\anita\AppData\Local\Programs\Python\Python37-32\lib\site-packages\telegram\utils\request.py", line 221, in _request_wrapper
    raise Unauthorized(message)
telegram.error.Unauthorized: Unauthorized
```

**Comment by Tkd-Alex** [comment]
I think It is a problem with your telegram token. 
Look at this:

https://github.com/python-telegram-bot/python-telegram-bot/issues/448
https://github.com/python-telegram-bot/python-telegram-bot/issues/926

**Comment by Belsea** [comment]
Gosh, you're right, I've mistaken an O with a zero. Thank you!
