### ISSUE TITLE
ConnectionResetError: [WinError 10054]

### ISSUE THREAD

**Issue by Belsea** [Tkd-Alex/Telegram-InstaPy-Scheduling#45]
Hi,
this appears at almost every execution when the program should send the sessional report in the bot chat. I've installed the same way on 3 different devices but only one shows this problem. 
Everything is up to date, connection is pretty stable and doesn't seem to be a firewall problem.
Can anyone help?
Thank you

```
Process Process-1:
Traceback (most recent call last):
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
ConnectionResetError: [WinError 10054] Connessione in corso interrotta forzatamente dall'host remoto

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 203, in _request_wrapper
    resp = self._con_pool.request(*args, **kwargs)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 70, in request
    **urlopen_kw)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\request.py", line 148, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 666, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\util\retry.py", line 347, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\packages\six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 617, in urlopen
    chunked=chunked)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 402, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\vendor\ptb_urllib3\urllib3\connectionpool.py", line 398, in _make_request
    httplib_response = conn.getresponse()
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 1321, in getresponse
    response.begin()
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\http\client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\socket.py", line 589, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 1052, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\ssl.py", line 911, in read
    return self._sslobj.read(len, buffer)
telegram.vendor.ptb_urllib3.urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Alice\Telegram-InstaPy-Scheduling\process.py", line 82, in run
    self.end(forced=False)
  File "C:\Users\Alice\Telegram-InstaPy-Scheduling\process.py", line 59, in end
    self.bot.send_message(self.chat_id, text='InstaPy Bot end at {}\nExecution time {}'.format(time.strftime("%X"), end-self.start))
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "C:\Users\Alice\AppData\Local\Programs\Python\Python37\lib\site-packages\telegram\utils\request.py", line 209, in _request_wrapper
    raise NetworkError('urllib3 HTTPError {0}'.format(error))
telegram.error.NetworkError: urllib3 HTTPError ('Connection aborted.', ConnectionResetError(10054, "Connessione in corso interrotta forzatamente dall'host remoto", None, 10054, None))
```

**Comment by Belsea** [comment]
This is still happening, even more frequently and on more setups.
