### ISSUE TITLE
Show results on End

### ISSUE THREAD

**Issue by akrhin** [Tkd-Alex/Telegram-InstaPy-Scheduling#46]
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/root/Telegram-InstaPy-Scheduling/process.py", line 82, in run
    self.end(forced=False)
  File "/root/Telegram-InstaPy-Scheduling/process.py", line 63, in end
    lines = f.readlines()
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 5352: ordinal not in range(128)

no result messages int telegram. Any ideas?

**Comment by akrhin** [comment]
process.py
62:  with open(log_file, "r") as f:
replaced by
62: with open(log_file, "r",encoding='utf-8',errors='ignore') as f:
