### ISSUE TITLE
Telegram Error

### ISSUE THREAD

**Issue by ArielEcker** [Tkd-Alex/Telegram-InstaPy-Scheduling#9]
Can you help me?

========= RESTART: C:\Ariel\2018\InstaPy-master\telegram-instapy.py =========
Traceback (most recent call last):
  File "C:\Ariel\2018\InstaPy-master\telegram-instapy.py", line 231, in <module>
    main()
  File "C:\Ariel\2018\InstaPy-master\telegram-instapy.py", line 204, in main
    updater = Updater(telegram_token)
  File "C:\Python 3.6.4\lib\site-packages\telegram\ext\updater.py", line 122, in __init__
    self.bot = Bot(token, base_url, request=self._request)
  File "C:\Python 3.6.4\lib\site-packages\telegram\bot.py", line 108, in __init__
    self.token = self._validate_token(token)
  File "C:\Python 3.6.4\lib\site-packages\telegram\bot.py", line 134, in _validate_token
    raise InvalidToken()
telegram.error.InvalidToken: Invalid token
>>>

**Comment by Tkd-Alex** [comment]
Follow #4 
Maybe it's only and error on your config file.
Anyway try to write your telegram token directly in token variable
